### ISSUE TITLE
listening for close events or errors

### ISSUE THREAD

**Issue by ORESoftware** [vesse/node-ldapauth-fork#46]
I got this stack trace

```

[2017-05-30 04:58:49.312] [ERROR] [default] - Error: This socket is closed
    at Socket._writeGeneric (net.js:683:19)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Socket.Writable.write (_stream_writable.js:247:11)
    at Socket.write (net.js:661:40)
    at Client._send (/usr/local/cdt/node_modules/ldapauth-fork/node_modules/ldapjs/lib/client/client.js:914:17)
    at Client.bind (/usr/local/cdt/node_modules/ldapauth-fork/node_modules/ldapjs/lib/client/client.js:367:15)
    at LdapAuth._adminBind (/usr/local/cdt/node_modules/ldapauth-fork/lib/ldapauth.js:171:21)
    at LdapAuth._search (/usr/local/cdt/node_modules/ldapauth-fork/lib/ldapauth.js:193:8)
    at LdapAuth._findUser (/usr/local/cdt/node_modules/ldapauth-fork/lib/ldapauth.js:253:8)
    at module.exports (/usr/local/cdt/middleware/auth.js:184:8)
    at Layer.handle [as handle_request] (/usr/local/cdt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/cdt/node_modules/express/lib/router/index.js:312:13)
    at /usr/local/cdt/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/local/cdt/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/local/cdt/node_modules/express/lib/router/index.js:271:10)
    at /usr/local/cdt/app.js:66:5
    at Layer.handle [as handle_request] (/usr/local/cdt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/cdt/node_modules/express/lib/router/index.js:312:13)
    at /usr/local/cdt/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/local/cdt/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/local/cdt/node_modules/express/lib/router/index.js:271:10)
    at serveStatic (/usr/local/cdt/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/usr/local/cdt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/cdt/node_modules/express/lib/router/index.js:312:13)
    at /usr/local/cdt/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/local/cdt/node_modules/express/lib/router/index.js:330:12)
```

I am hoping to listen for errors or close events like so:

```js
let ldap = new LdapAuth(config.ldap);
ldap.once('error', foo);
ldap.once('close', bar);
```

but apparently the ldap instance is not an event emitter. How can I listen for errors etc?

**Comment by vesse** [comment]
Which version are you using?  `LdapAuth` inherited `EventEmitter` in version 3.0. It does [re-emits](https://github.com/vesse/node-ldapauth-fork/blob/v4.0.0/lib/ldapauth.js#L150-L154) only [`error` events](https://github.com/vesse/node-ldapauth-fork/blob/v4.0.0/lib/ldapauth.js#L105-L106)
