### ISSUE TITLE
Cannot connect to LDAP with StartTLS

### ISSUE THREAD

**Issue by hplodur** [vesse/node-ldapauth-fork#59]
I'm running LDAP with StartTLS on port 389. When I'm trying to connect to LDAP I'm getting the following error message:
`ConfidentialityRequiredError: TLS confidentiality required`

Configuration:
```
server: {
    url: 'ldap://localhost:389',
    bindDN: 'cn=ldap,ou=services,dc=example,dc=com',
    bindCredentials: 'password',
    searchBase: 'ou=people,dc=example,dc=com',
    searchFilter: '(cn={{username}})',
    tlsOptions: {
        ca: [fs.readFileSync('/etc/pki/ca/ca.crt')]
    }
}
```

When changing configuration to:
```
server: { 
    url: 'ldaps://localhost:389',
    bindDN: 'cn=ldap,ou=services,dc=example,dc=com',
    bindCredentials: 'password',
    searchBase: 'ou=people,dc=example,dc=com',
    searchFilter: '(cn={{username}})',
    tlsOptions: {
      ca: [fs.readFileSync('/etc/pki/ca/ca.crt')]
    }
}
```

I'm getting error message:
`Error: socket hang up`

From the [ldapjs](http://ldapjs.org/client.html#starttls) documentation I've been able to find out that you need to initiate StartTLS:

```
var ldap = require('ldapjs');
var client = ldap.createClient({
  url: 'ldap://127.0.0.1:1389'
});
...
var opts = {
  ca: [fs.readFileSync('mycacert.pem')]
};

client.starttls(opts, function(err, res) {
  assert.ifError(err);

  // Client communication now TLS protected
});
```

It seems to me that this modules create the connection using ldapjs:
```
var ldap = require('ldapjs');
...
  this._adminClient = ldap.createClient(this.clientOpts);
  this._userClient = ldap.createClient(this.clientOpts);
```

I've tried to add starttls in the code:
```
  this._adminClient.starttls(opts.tlsOptions, function(err, res) {
    assert.ifError(err);
    // Client communication now TLS protected
  });
  ...
  this._uesrCleint.starttls(opts.tlsOptions, function(err, res) {
    assert.ifError(err);
    // Client communication now TLS protected
  });  
```
but that does not work
```
TypeError: Cannot convert undefined or null to object
    at wrapper (/opt/example/node_modules/wrappy/wrappy.js:27:14)
    at Client.starttls (/opt/example/node_modules/ldapjs/lib/client/client.js:880:14)
    at new LdapAuth (/opt/example/node_modules/ldapauth-fork/lib/ldapauth.js:105:21)
    at Strategy.handleAuthentication (/opt/example/node_modules/passport-ldapauth/lib/passport-ldapauth/strategy.js:272:10)
    at Strategy.authenticate (/opt/example/node_modules/passport-ldapauth/lib/passport-ldapauth/strategy.js:337:33)
    at attempt (/opt/example/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/opt/example/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/opt/example/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/example/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/example/node_modules/express/lib/router/route.js:112:3)
```

What am I doing wrong? Did I forgot something?

**Comment by vesse** [comment]
The example in `starttls` documentation indeed shows

```javascript
client.starttls(opts, function(err, res) {
});
``` 
but the function signature above is `starttls(options, controls, callback)` which matches the [implementation](https://github.com/joyent/node-ldapjs/blob/v1.0.1/lib/client/client.js#L874-L877).

Try using 

```javascript
this._adminClient.starttls(opts.tlsOptions, undefined, function(err, res) { });
```
instead. If the `controls` is not passed I do get the same error as you do, with `undefined` I get another error which is likely caused by my test server not supporting TLS.

Unfortunately there is not much more I can help you with as I've only used LDAP/SSL. However if you do get it working I would appreciate a PR that allows using either `ldaps`, or securing with TLS.

**Comment by hplodur** [comment]
Hi,

Sorry for the late reply. I think we are going forward after the change but still having problems. This is what am I getting now:

```
ConnectionError: 1__ldap://localhost:389 closed
    at /opt/manage/node_modules/ldapjs/lib/client/client.js:1277:17
    at Array.forEach (native)
    at Client._onClose (/opt/manage/node_modules/ldapjs/lib/client/client.js:1272:19)
    at Socket.g (events.js:292:16)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:509:12)
```

I did the simple test.js and it seems that if I'm doing all the queries inside the TLS:

```
  var client = ldap.createClient({url: 'ldap://localhost:389'});
  console.log('Starting TLS');
  client.starttls(options, undefined, function(err) {
    console.log('inside the starttls callback');
    client.bind(cn, pass, function (err) {
      cb(err === null, err);
    });
    client.search('ou=people,dc=example,dc=com', opts, function(err, res) {
      res.on('searchEntry', function(entry) {
        //console.log('entry: ' + JSON.stringify(entry.object));
        cb(entry.object, err);
      });
      res.on('searchReference', function(referral) {
        //console.log('referral: ' + referral.uris.join());
      });
      res.on('error', function(err) {
        //console.error('error: ' + err.message);
      });
      res.on('end', function(result) {
        //console.log('status: ' + result.status);
      });
    //  process.exit(1);
    });
  });
  client.unbind();
```

The only problem is that the connection is not closing.

**Comment by kopax** [comment]
If you find how to do, I would be interested to know your solution.

**Comment by hplodur** [comment]
@slvnperron yes you just need to client.unbind before res.on('end')
